version: '2'
services:
    microsergatewaydemo1-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/MicroserGatewayDemo1/mongodb/:/data/db/
